"""Initial migration

Revision ID: 55d9087c4442
Revises: 
Create Date: 2026-02-22 19:03:09.541014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55d9087c4442'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('title_slug', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('acceptance_rate', sa.Float(), nullable=True),
    sa.Column('total_accepted', sa.BigInteger(), nullable=True),
    sa.Column('total_submissions', sa.BigInteger(), nullable=True),
    sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_api_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_title_slug'), 'problems', ['title_slug'], unique=True)
    op.create_table('topic_prerequisites',
    sa.Column('topic_slug', sa.String(), nullable=False),
    sa.Column('prerequisite_of_slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('topic_slug', 'prerequisite_of_slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('real_name', sa.String(), nullable=True),
    sa.Column('leetcode_session', sa.Text(), nullable=True),
    sa.Column('leetcode_csrf', sa.Text(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('total_problems', sa.Integer(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('problem_topics',
    sa.Column('problem_id', sa.String(), nullable=False),
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.Column('topic_slug', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('problem_id', 'topic_name')
    )
    op.create_index(op.f('ix_problem_topics_topic_slug'), 'problem_topics', ['topic_slug'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('runtime_percentile', sa.Float(), nullable=True),
    sa.Column('memory_bytes', sa.BigInteger(), nullable=True),
    sa.Column('memory_percentile', sa.Float(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('runtime_error', sa.Text(), nullable=True),
    sa.Column('compile_error', sa.Text(), nullable=True),
    sa.Column('raw_api_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_problem_id'), 'submissions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_submissions_timestamp'), 'submissions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_table('submission_analyses',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('approach_name', sa.String(), nullable=True),
    sa.Column('approach_category', sa.String(), nullable=True),
    sa.Column('time_complexity', sa.String(), nullable=True),
    sa.Column('space_complexity', sa.String(), nullable=True),
    sa.Column('is_optimal', sa.Boolean(), nullable=True),
    sa.Column('interview_score', sa.Float(), nullable=True),
    sa.Column('mistake_type', sa.String(), nullable=True),
    sa.Column('mistake_detail', sa.Text(), nullable=True),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('llm_model_used', sa.String(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_analyses')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_timestamp'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_problem_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_problem_topics_topic_slug'), table_name='problem_topics')
    op.drop_table('problem_topics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('topic_prerequisites')
    op.drop_index(op.f('ix_problems_title_slug'), table_name='problems')
    op.drop_table('problems')
    # ### end Alembic commands ###
